name: Secret Scan

on:
  push:
    branches:
      - master
  workflow_dispatch:

jobs:
  security_scan:
    name: Security Scan
    runs-on: ubuntu-latest
    steps:
      - name: Import Ubuntu
        uses: actions/setup-python@v2
        with:
          python-version: '3.x'

      - name: Install TruffleHog
        run: pip install trufflehog

      - name: Verify TruffleHog Installation
        run: trufflehog -h

      - name: Run TruffleHog Scan
        run: trufflehog  ${{ github.workspace }}

