name: Secret Scanning

on:
  push:
    branches:
      - main

jobs:
  scan-secrets:
    runs-on: ubuntu-latest

    steps:
      - name: Install Python dependencies
        run: |
          python -m pip install --upgrade pip
          pip install trufflehog

      - name: Clone the repository
        uses: actions/checkout@v2

      - name: Show cloned repository path
        run: ls -R ${{ github.workspace }}

      - name: Perform Trufflehog scan
        run: |
          cd ${{ github.workspace }}
          trufflehog --regex --entropy=True --json > output.json

      - name: Convert output to text format
        run: |
          cd ${{ github.workspace }}
          trufflehog --regex --entropy=True --json > output.json
          trufflehog --json output.json --format txt > output.txt

      - name: Upload output as artifact
        uses: actions/upload-artifact@v2
        with:
          name: secret-scan-results
          path: ${{ github.workspace }}/output.txt

      - name: Delete the cloned repository
        run: rm -rf ${{ github.workspace }}
